name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CMake
      run: mkdir -p build && cd build && cmake ..
    - name: Check Format
      working-directory: ${{github.workspace}}/build
      run: make check-format
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j
    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: make test