name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CMake
      run: mkdir -p build && cd build && cmake ..
    - name: Make Format
      working-directory: ${{github.workspace}}/build
      run: make format
    - name: Check for uncommitted changes caused by formatting
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Error: Some files are not formatted correctly. Please run 'make format' and commit the changes."
          git status --short
          exit 1
        fi
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j
    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: make test